import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";
import Footer from "./(components)/Footer/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
import SHOPCO from "@/app/imgs/SHOP.CO.png";
import Head from "next/head";
export const metadata: Metadata = {
  title: "SHOP.CO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <link rel="icon" href="./SHOP.CO.png" type="image/png" />
        </Head>
        <body>
          <Navbar />
          {children}
          <Toaster />

          <Footer />
        </body>
      </html>
    </ClerkProvider>

    // <html lang="en">
    //   <body className={inter.className}>
    //     <Navbar />
    //     {children}
    //     <Footer />
    //   </body>
    // </html>
  );
}
